import React, { useState } from 'react';
import styles from './ComplianceGenerator.module.css';
import { apiService } from '/src/api';
import type { ComplianceDocumentResponse } from '/src/types';

interface ComplianceGeneratorProps {
  grantId: number;
  grantName: string;
  onGenerateComplete?: (document: ComplianceDocumentResponse) => void;
}

const ComplianceGenerator: React.FC<ComplianceGeneratorProps> = ({
  grantId,
  grantName,
  onGenerateComplete
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [complianceDocument, setComplianceDocument] = useState<ComplianceDocumentResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateComplianceDocument = async () => {
    setIsGenerating(true);
    setError(null);
    
    try {
      const document = await apiService.generateComplianceDocument(grantId);
      setComplianceDocument(document);
      onGenerateComplete?.(document);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate compliance document');
    } finally {
      setIsGenerating(false);
    }
  };

  const getComplianceColor = (score: number) => {
    if (score >= 0.9) return '#4CAF50'; // Excellent - Green
    if (score >= 0.7) return '#FF9800'; // Good - Orange
    if (score >= 0.5) return '#FF5722'; // Fair - Red-Orange
    return '#F44336'; // Poor - Red
  };

  const getComplianceLabel = (score: number) => {
    if (score >= 0.9) return 'Excellent';
    if (score >= 0.7) return 'Good';
    if (score >= 0.5) return 'Fair';
    return 'Needs Improvement';
  };

  const downloadDocument = () => {
    if (!complianceDocument) return;
    
    const content = `
# Compliance Report - ${grantName}

**Generated:** ${new Date(complianceDocument.generated_at).toLocaleDateString()}
**Compliance Score:** ${(complianceDocument.compliance_score * 100).toFixed(1)}%

## Summary
${complianceDocument.compliance_summary}

## Key Requirements
${complianceDocument.key_requirements.map(req => `- ${req}`).join('\n')}

---
*Generated by AstraFund AI Document Intelligence*
    `.trim();
    
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-report-${grantName.replace(/\s+/g, '-').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <div className={styles.titleSection}>
          <h3 className={styles.title}>📋 Compliance Document Generator</h3>
          <p className={styles.subtitle}>
            Generate AI-powered compliance reports for {grantName}
          </p>
        </div>
        
        <button
          onClick={generateComplianceDocument}
          disabled={isGenerating}
          className={styles.generateButton}
        >
          {isGenerating ? 'Generating...' : 'Generate Report'}
        </button>
      </div>

      {error && (
        <div className={styles.errorMessage}>
          <span className={styles.errorIcon}>⚠️</span>
          {error}
        </div>
      )}

      {complianceDocument && (
        <div className={styles.results}>
          <div className={styles.resultsHeader}>
            <h4 className={styles.resultsTitle}>📊 Compliance Report Generated</h4>
            <div className={styles.complianceScore}>
              <span 
                className={styles.scoreValue}
                style={{ color: getComplianceColor(complianceDocument.compliance_score) }}
              >
                {(complianceDocument.compliance_score * 100).toFixed(1)}%
              </span>
              <span 
                className={styles.scoreLabel}
                style={{ color: getComplianceColor(complianceDocument.compliance_score) }}
              >
                {getComplianceLabel(complianceDocument.compliance_score)}
              </span>
            </div>
          </div>

          <div className={styles.complianceSummary}>
            <h5 className={styles.sectionTitle}>📝 Summary</h5>
            <div className={styles.summaryContent}>
              {complianceDocument.compliance_summary}
            </div>
          </div>

          <div className={styles.requirements}>
            <h5 className={styles.sectionTitle}>✅ Key Requirements</h5>
            <ul className={styles.requirementsList}>
              {complianceDocument.key_requirements.map((requirement, index) => (
                <li key={index} className={styles.requirement}>
                  {requirement}
                </li>
              ))}
            </ul>
          </div>

          <div className={styles.actions}>
            <button
              onClick={downloadDocument}
              className={styles.downloadButton}
            >
              📥 Download Report
            </button>
            <div className={styles.metadata}>
              <span className={styles.metadataItem}>
                Generated: {new Date(complianceDocument.generated_at).toLocaleString()}
              </span>
              <span className={styles.metadataItem}>
                Document ID: {complianceDocument.document_id}
              </span>
            </div>
          </div>
        </div>
      )}

      <div className={styles.features}>
        <h5 className={styles.featuresTitle}>🤖 AI-Powered Analysis</h5>
        <div className={styles.featureList}>
          <div className={styles.feature}>
            <span className={styles.featureIcon}>📊</span>
            <span>Comprehensive Compliance Scoring</span>
          </div>
          <div className={styles.feature}>
            <span className={styles.featureIcon}>🔍</span>
            <span>Automated Requirement Extraction</span>
          </div>
          <div className={styles.feature}>
            <span className={styles.featureIcon}>📋</span>
            <span>Professional Report Generation</span>
          </div>
          <div className={styles.feature}>
            <span className={styles.featureIcon}>💡</span>
            <span>Actionable Insights & Recommendations</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ComplianceGenerator;
